# Numpy First Program

In [2]:
import numpy as np


arr = np.array([1, 2, 3, 4])
print(arr)
print(arr + 5)
print(arr * 8)
print(arr.mean())
print(arr.sum())

[1 2 3 4]
[6 7 8 9]
[ 8 16 24 32]
2.5
10


In [3]:
arr = np.array([23, 64, 598, 84, 87, 45])
print(arr)
print(arr + 5)
print(arr * 8)
print(arr.mean())
print(arr.sum())


[ 23  64 598  84  87  45]
[ 28  69 603  89  92  50]
[ 184  512 4784  672  696  360]
150.16666666666666
901


# 2D Array Matrix

In [5]:
arr2 = np.array([[6, 74, 43, 89, 75, 75], [75, 87, 45, 87, 56, 64]])

print(arr2)
print(0, 6)

[[ 6 74 43 89 75 75]
 [75 87 45 87 56 64]]
0 6


# random Row and column

In [7]:
random = np.ones((4, 7))
print("seven Array :", random)

seven Array : [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


# Zero Row and Column

In [9]:
random = np.zeros((4, 6))
print("seven Array :", random)

seven Array : [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# same Value

In [14]:
arr = np.eye(11)
print("Identity :",arr)

Identity : [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Full Value 

In [12]:
full = np.full((4,5) , 6)
print("Full value is :" , full)

Full value is : [[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
